### ISSUE TITLE
плагин не видит файл с переводом

### ISSUE THREAD

**Issue by xneoseven** [Mirik9724/whitelist-ultra#1]
или че-то такое хз
настройки плагина по умолчанию, ядро Paper 1.21.4
`/wlu add 123`
![image](https://github.com/user-attachments/assets/d21e0f23-d767-44c2-9993-bc80d8c1a138)
`/wlu remove 123` работает нормально
![image](https://github.com/user-attachments/assets/9a212a67-f28b-4125-a59d-c834c1f0137b)

**Comment by Mirik9724** [comment]
смотри я коде накосячил думаю в сегодняшнем билде исправлю

**Comment by Mirik9724** [comment]
удалите файл переводов и перезапустите сервер
